const wbcity = [
	'Adra',
    'Agarpara',
	'Alipurduar',
    'Andul',
	'Arambagh',
	'Asansol',
    'Baghajatin',
    'Baguihati',
	'Baharampur',
	'Balurghat',
    'Bangur',
	'Bankura',
    'Barasat',
    'Baranagar',
    'Barrackpore',
    'Baruipur',
    'Behala',
    'Beleghata',
    'Belgachia',
    'Belgharia',
    'Bhawanipur',
    'Bolpur',
    'Birati',
    'Bisharpara',
    'Budgebudge',
    'Caning',
    'Chakdah',
    'Chuchura',
    'Cooch Behar',
    'Dankuni',
	'Darjeeling',
    'Dumdum',
    'Dunlop',
    'Durganagar',
    'Diamond Harbour',
    'Digha',
	'English Bazar',
    'Esplanade',
    'Garden reach',
    'Garia',
	'Gangarampur',
    'Girishpark',
    'Halisahar',
    'Howrah',
    'Hooghly',
	'Habra',
    'Hedua',
	'Hugli-Chinsurah',
	'Jalpaiguri',
	'Jhargram',
    'Kachrapara',
    'Kalighat',
	'Kalimpong',
    'Kalyani',
    'Kasba',
    'Keshtopur',
	'Kharagpur',
    'Khardah',
    'Khidderpore',
	'Kolkata',
    'Krishnanagar',
    'Madhyamgram',
	'Mainaguri',
	'Malda',
    'Maniktala',
	'Mathabhanga',
	'Medinipur',
	'Memari',
	'Monoharpur',
	'Murshidabad',
	'Nabadwip',
	'Naihati',
    'Newtown',
    'New Barrackpore',
    'Noapara',
    'Park Street',
	'Panchla',
	'Pandua',
	'Purulia',
	'Paschim Punropara',
    'Patuli',
	'Raghunathpur',
	'Raghunathganj',
	'Raiganj',
	'Rampurhat',
	'Ranaghat',
    'Rajarhat',
    'Rabindrasadan',
    'Saltlake',
	'Sainthia',
	'Santipur',
    'Sealdah',
    'Shyambazar',
	'Siliguri',
    'Sodpur',
	'Sonamukhi',
    'Sonarpur',
    'Sovabazar',
	'Srirampore',
	'Suri',
	'Taki',
	'Tamluk',
	'Tarakeswar',
    'Tollygunge'
];

export default wbcity;
