const wbcity = [
  'Adra',
  'Agarpara',
  'Alipurduar',
  'Andul',
  'Arambagh',
  'Asansol',
  'Baghajatin',
  'Baguihati',
  'Baharampur',
  'Balurghat',
  'Bandel',
  'Bangur',
  'Bankura',
  'Barasat',
  'Baranagar',
  'Barrackpore',
  'Baruipur',
  'Basirhat',
  'Behala',
  'Beleghata',
  'Belgachia',
  'Belgharia',
  'Bhawanipur',
  'Birati',
  'Birbhum',
  'Bisharpara',
  'Bolpur',
  'Bullygunj',
  'Budgebudge',
  'Caning',
  'Chakdah',
  'Chandannagar',
  'Chuchura',
  'Cooch Behar',
  'Dakkhineshwar',
  'Dankuni',
  'Darjeeling',
  'Dumdum',
  'Dunlop',
  'Durganagar',
  'Diamond Harbour',
  'Digha',
  'English Bazar',
  'Entally',
  'Esplanade',
  'Exide',
  'Garden reach',
  'Garia',
  'Gangarampur',
  'Girishpark',
  'Halisahar',
  'Hazra',
  'Howrah',
  'Hooghly',
  'Habra',
  'Hedua',
  'Hugli-Chinsurah',
  'Ichapur',
  'Jadavpur',
  'Jalpaiguri',
  'Jatindas Park',
  'Jhargram',
  'Kachrapara',
  'Kalighat',
  'Kalimpong',
  'Kalyani',
  'Kasba',
  'Keshtopur',
  'Kharagpur',
  'Khardah',
  'Khidderpore',
  'Kolaghat',
  'Kolkata',
  'Krishnanagar',
  'Madhyamgram',
  'Mainaguri',
  'Malda',
  'Maniktala',
  'Mathabhanga',
  'Medinipur',
  'Memari',
  'Monoharpur',
  'Murshidabad',
  'Nabadwip',
  'Naihati',
  'Newtown',
  'New Barrackpore',
  'Noapara',
  'Palta',
  'Panchla',
  'Pandua',
  'Park Circus',
  'Park Street',
  'Purulia',
  'Paschim Punropara',
  'Patuli',
  'Raghunathpur',
  'Raghunathganj',
  'Raiganj',
  'Rampurhat',
  'Ranaghat',
  'Rajarhat',
  'Rabindrasadan',
  'Rishra',
  'Saltlake',
  'Sainthia',
  'Santipur',
  'Science City',
  'Sealdah',
  'Shyambazar',
  'Siliguri',
  'Sodpur',
  'Sonamukhi',
  'Sonarpur',
  'Sovabazar',
  'Srirampore',
  'Suri',
  'Taki',
  'Tamluk',
  'Tarakeswar',
  'Tollygunge',
  'Uttarpara',
];

export default wbcity.sort();
